-- AlterTable
ALTER TABLE `notificaciones` MODIFY `tipo` ENUM('NUEVA_ASIGNACION', 'RECORDATORIO', 'VENCIMIENTO_PROXIMO', 'AUDITORIA_VENCIDA', 'RESULTADO_PUBLICADO', 'APROBACION_PENDIENTE', 'SISTEMA', 'ASIGNACION_MENSUAL_CORREO', 'RESULTADO_MENSUAL_CORREO') NOT NULL;
