import { Router } from 'express';
import { autenticar } from '../../middlewares/autenticacion';
import { autorizarRoles } from '../../middlewares/autorizacion';
import { ROLES_ADMIN_NEGOCIO, ROLES_QUE_CONSULTAN_AUDITORIAS, ROLES_QUE_EJECUTAN_AUDITORIAS } from '../../utils/permisos';
import { listarAsignaciones } from './01_listar';
import { crearAsignacion } from './02_crear';
import { publicarAsignacion } from './03_publicar';
import { reasignar } from './04_reasignar';
import { crearEnlaceInvitado, obtenerEnlaceInvitadoActivo, revocarEnlaceInvitadoActivo } from './05_crear_enlace';
import { obtenerContextoAuditoriaAsignacion } from './07_contexto_auditoria';
import { obtenerAsignacionesMensuales } from './08_mensual';
import { guardarAsignacionMensualArea } from './09_guardar_mensual';
import { autoasignarMensual } from './10_autoasignar_mensual';
import { obtenerCargaMensual } from './11_carga_mensual';
import { reabrirAsignacion } from './12_reabrir';

export const asignacionesRouter = Router();

asignacionesRouter.use(autenticar);
asignacionesRouter.get('/mensual', autorizarRoles(...ROLES_ADMIN_NEGOCIO), obtenerAsignacionesMensuales);
asignacionesRouter.get('/mensual/carga', autorizarRoles(...ROLES_ADMIN_NEGOCIO), obtenerCargaMensual);
asignacionesRouter.post('/mensual/autoasignar', autorizarRoles(...ROLES_ADMIN_NEGOCIO), autoasignarMensual);
asignacionesRouter.put('/mensual/:areaId', autorizarRoles(...ROLES_ADMIN_NEGOCIO), guardarAsignacionMensualArea);
asignacionesRouter.get('/', autorizarRoles(...ROLES_QUE_CONSULTAN_AUDITORIAS), listarAsignaciones);
asignacionesRouter.get('/:id/auditoria', autorizarRoles(...ROLES_QUE_EJECUTAN_AUDITORIAS), obtenerContextoAuditoriaAsignacion);
asignacionesRouter.get('/:id/enlaces-invitado/activo', autorizarRoles(...ROLES_QUE_EJECUTAN_AUDITORIAS), obtenerEnlaceInvitadoActivo);
asignacionesRouter.post('/:id/enlaces-invitado', autorizarRoles(...ROLES_QUE_EJECUTAN_AUDITORIAS), crearEnlaceInvitado);
asignacionesRouter.delete('/:id/enlaces-invitado/activo', autorizarRoles(...ROLES_QUE_EJECUTAN_AUDITORIAS), revocarEnlaceInvitadoActivo);
asignacionesRouter.post('/', autorizarRoles(...ROLES_ADMIN_NEGOCIO), crearAsignacion);
asignacionesRouter.post('/:id/publicar', autorizarRoles(...ROLES_ADMIN_NEGOCIO), publicarAsignacion);
asignacionesRouter.post('/:id/reasignar', autorizarRoles(...ROLES_ADMIN_NEGOCIO), reasignar);
asignacionesRouter.post('/:id/reabrir', autorizarRoles(...ROLES_ADMIN_NEGOCIO), reabrirAsignacion);
